--sys_config系统配置表
--关于校促会隐私的字段设置表
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (23, 0, DEFAULT, '校友会配置', 'local_platform_config', null, 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (24, 23, DEFAULT, '校友会隐私配置', 'local_platform_privcay_sttting', null, 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (25, 24, DEFAULT, '简介', 'description', 'LocalPlatformDetailVo', 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (26, 24, DEFAULT, '会员数量', 'memberCount', 'LocalPlatformDetailVo', 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (27, 24, DEFAULT, '负责人姓名', 'principalName', 'LocalPlatformDetailVo', 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (28, 24, DEFAULT, '负责人职务', 'principalPosition', 'LocalPlatformDetailVo', 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)
INSERT INTO cni_alumni.sys_config (config_id, parent_id, ancestors, config_name, config_key, config_value, data_type, is_system, status, remark, create_time, update_time, is_delete) VALUES (29, 24, DEFAULT, '联系电话', 'local_platform_phone', 'LocalPlatformDetailVo', 'STRING', 0, '1', null, DEFAULT, DEFAULT, DEFAULT)

